apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pam-tsbx-front"
  namespace: "teampam"
  labels:
    "team": "teampam"
spec:
  image: {{image}}
  port: 9111
  liveness:
    path: "/internal/isalive"
    initialDelay: 10
    timeout: 60
  readiness:
    path: "/internal/isready"
    initialDelay: 10
    timeout: 60
  preStopHook:
    http:
      path: "/internal/stop"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - "https://pam-tsbx-front.dev.intern.nav.no"

  accessPolicy:
    outbound:
      external:
        - host: oidc-ver2.difi.no

  idporten:
    enabled: true

    # optional, default shown
    clientURI: "https://pam-tsbx-front.dev.intern.nav.no"

    # optional, default shown
    redirectPath: "/oauth2/callback"

    # optional, default shown
    frontchannelLogoutPath: "/oauth2/logout"

    # optional, defaults shown
    postLogoutRedirectURIs:
      - "https://tsbx-front.dev.intern.nav.no/loggedout"

    # optional, in seconds - defaults shown (1 hour)
    accessTokenLifetime: 3600

    # optional, in seconds - defaults shown (2 hours)
    sessionLifetime: 7200
