apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pam-tsbx-front"
  namespace: "teampam"
  labels:
    "team": "teampam"
spec:
  image: {{image}}
  port: 9111
  liveness:
    path: "/internal/isalive"
    initialDelay: 10
    timeout: 60
  readiness:
    path: "/internal/isready"
    initialDelay: 10
    timeout: 60
  preStopHook:
    http:
      path: "/internal/stop"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    - {{ingress}}
  env:
    - name: IDPORTEN_POST_LOGOUT_URI
      value: {{ingress}}

  idporten:
    enabled: true

    # optional, in seconds - defaults shown (1 hour)
    accessTokenLifetime: 3600

    postLogoutRedirectURIs:
      - {{ingress}}

    # optional, in seconds - defaults shown (2 hours)
    sessionLifetime: 7200

  # Enable communication with pam-tsbx-api through use of token exchange with Tokendings (local OAuth server in NAV infrastructure)
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: pam-tsbx-api
